use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'XCNetworking_Example' do
  pod 'XCNetworking', :path => '../'

  target 'XCNetworking_Tests' do
    inherit! :search_paths

    
  end
end
